### ISSUE TITLE
git remote branch 이름 변경

### ISSUE THREAD

**Issue by aeiou8668** [lbj122/studySpring#4]
git remote branch명을 변경하고 source tree에서 변경 전후를 비교해보고 관련 내용 댓글로 달아주세요.
좀 더 명확하게 자신있게 사용할 수 있게 될꺼에요~~

너무 급하게 사용해서 뭔지 모르고 사용했던 1인의 말이었습니다 ㅋㅋㅋ

**Comment by aeiou8668** [comment]
https://git-scm.com/book/ko/v2/Git-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EB%A6%AC%EB%AA%A8%ED%8A%B8-%EB%B8%8C%EB%9E%9C%EC%B9%98

**Comment by lbj122** [comment]
완료했습니다. (master --> spring 변경).
로컬 branch 명 변경 --> remote branch 삭제 --> push local branch

**Comment by aeiou8668** [comment]
확인했습니다. close합니다.
